language: vi
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 150
- name: ResponseSelector

policies:
  - name: TEDPolicy
    epochs: 350
    max_history: 5
  - name: MemoizationPolicy
    max_history: 3
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.1
    core_threshold: 0.2
    fallback_action_name: 'utter_default'
  - name: FormPolicy
